name: Build and upload nightly ipa

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26.0"
      - name: Install Xcode platforms
        run: |
          xcrun simctl list > /dev/null # fixes next command sometimes failing
          xcodebuild -downloadPlatform iOS
      - name: Get commit SHA
        id: commitinfo
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build
        run: xcodebuild -scheme "Aidoku (iOS)" -configuration Release archive -archivePath build/Aidoku.xcarchive -skipPackagePluginValidation CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - name: Package ipa
        run: |
          mkdir Payload
          cp -r build/Aidoku.xcarchive/Products/Applications/Aidoku.app Payload
          zip -r Aidoku-iOS_nightly-${{ steps.commitinfo.outputs.sha_short }}.ipa Payload
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Aidoku-iOS_nightly-${{ steps.commitinfo.outputs.sha_short }}.ipa
          path: Aidoku-iOS_nightly-${{ steps.commitinfo.outputs.sha_short }}.ipa
          if-no-files-found: error
